Define proxy mapping state more rigorously
tfpauly/quic-proxy pull request #24
Opened 2020-10-15 17:18 UTC by tfpauly

Addressing #23, #22, #21, #20

2020-10-15 21:16 UTC, LPardue reviewed
This is super helpful. Thanks. 

I've got suggestions for nits. But also there's some things I think could be improvements.

2020-10-15 21:16 UTC, LPardue commented on draft-pauly-connect-quic.md
> +authority pseudo-header. If any of these is missing, the proxy MUST reject the
See earlier comment about more terse terms. We could then tighten this up to say soemthing "The proxy MUST validate that the CONNECT-QUIC request is either type X or Y..."

2020-10-15 21:16 UTC, LPardue commented on draft-pauly-connect-quic.md
>  direction, MUST cancel its CONNECT-QUIC HTTP/3 request {{!I-D.ietf-quic-http}}.
This section reads a little weird. I'll make a spin off issueo work on improvements for talking about request stream lifecycle; it should also cover the similar stuff described in H3's CONNECT section like what frames are valid.

2020-10-15 21:20 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +- Datagram flow, which is a flow of QUIC DATAGRAM frames specific to a single client QUIC connection to the proxy.
```suggestion
- Datagram flow, which is a flow of HTTP/3 DATAGRAMs specific to a single client QUIC connection to the proxy.
```

2020-10-15 22:22 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +target.
I just tried arranging it the other way, but I think it was less clear. It flows right now as:
- Text description of the mapping requirement
- Diagram of the mapping
- Explanation for what the mapping means

2020-10-15 22:23 UTC, LPardue commented on draft-pauly-connect-quic.md
> +target.
Yeah that works for me.

2020-10-15 22:24 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +authority pseudo-header. If any of these is missing, the proxy MUST reject the
Yeah, I think I may leave that for a later editorial cleanup. I am hesitant to add too much jargon yet.

2020-10-15 22:25 UTC, tfpauly commented on draft-pauly-connect-quic.md
>  direction, MUST cancel its CONNECT-QUIC HTTP/3 request {{!I-D.ietf-quic-http}}.
Sounds good, new issue welcome (and text welcome too!)

2020-10-15 22:25 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +packets to the requested Server Connection ID, but only use tunnelled mode.
Fixed this up!

2020-10-15 22:34 UTC, DavidSchinazi requested changes
Thanks for writing this, it really addresses a lot of things! Sorry about the mountain of comments, many are editorial but some are design issues that we'd need to address if we want to resolve the 4 issues

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +This mapping guarantees that any QUIC packet sent from the client to the proxy in tunnelled mode can be sent to the correct
Well technically the client could send a packet with a flow ID that's unknown to the server

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +- Client-facing socket, which is the set of UDP addresses and ports used to communicate between the client and the proxy.
Our implementation doesn't use connected sockets on the server - each QUIC server has a single client-facing non-connected UDP socket. Maybe just mentioning somewhere that this spec uses "socket" as a way to refer to a 4-tuple and that it can be implemented a variety of ways

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +(Server-facing socket + Client Connection ID) => Client-facing socket
I don't think that's right, the mapping should be to a QUIC connection, not a client-facing socket - because multiple QUIC connections can share a client-facing socket

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +server-facing socket for every proxied QUIC connection. The mapping is critical for any case where server-facing
I'm not sure we've defined the term "proxied QUIC connection" anywhere. I ask because that's a concept that the proxy doesn't really have access to - the proxy can't distinguish between "two CIDs belonging to one connection" vs "two connections" if only short headers are involved

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +psuedo-header identifying the target. All requests for the same QUIC
```suggestion
pseudo-header identifying the target. All requests for the same QUIC
```

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +Connection between a client and a target SHOULD contain the same Datagram-Flow-Id
Why is this a SHOULD and not a MUST? It's required for correctness

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +and authority. Any mismatch in these would cause the proxy to treat the requests
We should address the discrepancy between authority and server-facing 4-tuple, they're not quite the same because DNS can return multiple results so we need to mention that the proxy has to save the authority in the mappings and reuse the DNS result from the first time around. (I'm also realizing the proxy really shouldn't perform happy eyeballs here because that would make things way more complicated)

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +The first request the clients makes MUST contain the authority psuedo-header and the
```suggestion
The first request the clients makes MUST contain the authority pseudo-header and the
```

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +It can reject requests that would cause a conflict and indicate this to the client by replying with a
We should define the term of "conflict" before using it. It particular, one CID being a prefix of another is a "conflict" for the purposes of this draft.

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +If the client receives an error, such as a 409 (Conflict) response, it MUST NOT forward
This is ambiguous: the server could decide to reject the request because it doesn't like the authority (e.g. if the client sends "localhost" as the authority, the proxy really ought to refuse to proxy there). Another example is DNS failure. I think that we need a way to convey the scenario where "the proxy agrees to proxy to this authority and has opened a target-facing socket, but cannot use forwarding mode due to a conflict".

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +Once a Client Connection ID has been accepted by the proxy, the client MUST be prepared to
As discussed in #23, it would be great to allow clients to disable forwarding mode

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +if the requested datagram flow ID has already been used on that client QUIC connection
```suggestion
if the requested datagram flow ID has already been used on that client-to-proxy QUIC connection
```

2020-10-15 22:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +Client Connection ID and the selected server-facing socket is unique, the proxy creates
I would phrase this as "avoiding conflict" instead of "unique" because conflicts here aren't only about equality

2020-10-15 22:38 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +(Server-facing socket + Client Connection ID) => Client-facing socket
Yes, that's correct—and the QUIC connection implies the client-facing socket and datagram flow ID. Can switch the language.

2020-10-15 22:40 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +Connection between a client and a target SHOULD contain the same Datagram-Flow-Id
So, my thought here was that a client _could_ decide to be sneaky and represent what is one connection between the client and the target as two subsequent flows to proxy, which could make it "migrate". It'd be some paranoid privacy thing, but I could see a reason it would be illegal as long as the client followed the rest of the rules.

2020-10-15 22:41 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +a NEW_CONNECTION_ID frame.
```suggestion
A client can add new Connection IDs to a proxied QUIC connection by sending
a NEW_CONNECTION_ID frame to the target.
```

2020-10-15 22:43 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +Once a Client Connection ID has been accepted by the proxy, the client MUST be prepared to
So my thought here is that disabling forwarding is essentially just using CONNECT-UDP (which is fine). My question is if that is a separate method, like CONNECT-UDP, or if it is a CONNECT-QUIC request that has a flow ID and authority but no connection ID.

2020-10-15 22:43 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +if the requested datagram flow ID has already been used on that client QUIC connection
```suggestion
if the requested datagram flow ID has already been used on that client <-> proxy QUIC connection
```

2020-10-15 22:44 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +Client Connection ID and the selected server-facing socket is unique, the proxy creates
```suggestion
Client Connection ID and the selected server-facing socket does not create a conflict, the proxy creates
```

2020-10-15 22:45 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +and the client-facing socket on which the request was received is unique, the proxy
```suggestion
and the client-facing socket on which the request was received does not create a conflict, the proxy
```

2020-10-15 23:18 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +being used by proxied connections, along with the sockets (UDP addresses and ports)
Clarified

2020-10-15 23:18 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +Each datagram flow MUST be mapped to a single server-facing socket. This datagram flow can be identified by datagram flow ID
Updated the mapping to that!

2020-10-15 23:20 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +This mapping guarantees that any QUIC packet sent from the client to the proxy in tunnelled mode can be sent to the correct
Clarified the text to be about this particular flow ID

2020-10-15 23:21 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +(Server-facing socket + Client Connection ID) => Client-facing socket
Updated the mappings. I think there are still two mappings — one to the QUIC Connection + Datagram Flow ID, and one to the client-facing socket (for forwarding).

2020-10-15 23:22 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +- Client-facing socket, which is the set of UDP addresses and ports used to communicate between the client and the proxy.
Added a note about what the term "socket" means for this document.

2020-10-15 23:23 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +server-facing socket for every proxied QUIC connection. The mapping is critical for any case where server-facing
Changed this to refer to the datagram flow ID, which is what it actually knows.

2020-10-15 23:23 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +and authority. Any mismatch in these would cause the proxy to treat the requests
Added a paragraph about this in the proxy behavior section, since it really belongs there (the client doesn't really care)

2020-10-15 23:24 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +It can reject requests that would cause a conflict and indicate this to the client by replying with a
Added a section early on (in state requirements) about what conflicts mean.

2020-10-15 23:27 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +If the client receives an error, such as a 409 (Conflict) response, it MUST NOT forward
Requests that include Server-Connection-Id are only about opening up forwarding paths, not creating new upstream connections. Thus, I think the correct response here is to not forward, whatever the particular error code; assuming that you already were able to open up a tunneling path with the earlier request.

2020-10-15 23:33 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +(Server-facing socket + Client Connection ID) => Client-facing socket
Good point, agreed.

2020-10-15 23:34 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +server-facing socket for every proxied QUIC connection. The mapping is critical for any case where server-facing
Thanks, I like that.

2020-10-15 23:37 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +Connection between a client and a target SHOULD contain the same Datagram-Flow-Id
That makes sense for the flow ID, but not for the authority - perhaps we say MUST be sent to the same authority and SHOULD be sent to the same Datagram-Flow-Id?

2020-10-15 23:39 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +If a proxy reuses server-facing sockets, it SHOULD store which authorities (server names)
```suggestion
If a proxy reuses server-facing sockets, it SHOULD store which authorities (which could be a domain name or IP address literal)
```

2020-10-15 23:39 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +new DNS query and potentially choosing a different server IP address.
```suggestion
new DNS query and potentially choosing a different server IP address which could map to a different server.
```

2020-10-15 23:40 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +and authority. Any mismatch in these would cause the proxy to treat the requests
Agreed, that's a better spot for it - I'll create new comments over there.

2020-10-15 23:43 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +
I'd suggest adding some text about how the server needs to resolve domain name authorities to IP addresses in the first place, we have text for reusing sockets but this might warrant its own paragraph

2020-10-15 23:43 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +It can reject requests that would cause a conflict and indicate this to the client by replying with a
New text LGTM

2020-10-15 23:46 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +If the client receives an error, such as a 409 (Conflict) response, it MUST NOT forward
I think this complicates the design - I'd rather think about any request being able to open up any mapping or socket - and I'd rather not use 4xx to indicate partial success - there are probably implementations out there that close the stream if the response isn't 2xx.

2020-10-15 23:49 UTC, DavidSchinazi commented on draft-pauly-connect-quic.md
> +Once a Client Connection ID has been accepted by the proxy, the client MUST be prepared to
I think there's value in using CONNECT-QUIC without forwarding: one is allowing the proxy to only need one socket, another is if we decide to later add short header connection ID compression to CONNECT-QUIC

2020-10-16 00:21 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +
Added some text on this above!

2020-10-16 00:22 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +QUIC Initial packet and chooses a Connection ID that is too short or hits a conflict
Removed that bit—it's now explained in the "conflicts" section.

2020-10-16 15:51 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +Once a Client Connection ID has been accepted by the proxy, the client MUST be prepared to
Okay, updated text to allow either side to opt out of forwarding!

2020-10-16 15:52 UTC, tfpauly commented on draft-pauly-connect-quic.md
> +If the client receives an error, such as a 409 (Conflict) response, it MUST NOT forward
Updated the text to clarify this. The stream will indeed be closed and failed with any 4xx response (that just doesn't invalidate a separate stream that requested non-forwarding proxying to the same authority).

2020-10-16 17:19 UTC, LPardue commented on draft-pauly-connect-quic.md
> +A clients sends new CONNECT-QUIC requests when it wants to start
```suggestion
A client sends new CONNECT-QUIC requests when it wants to start
```

2020-10-16 18:03 UTC, DavidSchinazi approved these changes
Thanks for the discussion and edits! Approved modulo a few small suggestions

2020-10-16 18:10 UTC, merged